### ISSUE TITLE
Mikropalvelussa olevan Vie-napin värinmuutos

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/koha-plugin-broadcast-biblios#1]
Onnistuisiko Mikropalvelussa muokata Vie-nappia värikkäämmäksi esim. vihreäksi? Tällä hetkellä napin väri on niin vaalea, että napissa olevaa tekstiä on vaikea erottaa. Näytöllä nappi näkyy valkeana. Tässä kuvakaappauksessa se näkyy harmaana:

![Vie-nappi](https://github.com/KohaSuomi/KohaSuomiServices/assets/98805552/c945de47-e1b7-4035-947b-d16647906da4)

Napin väri katosi vuoden 2023 versiopäivityksessä. 

Tämän tiketin lopussa on tuosta napin väristä käyty keskustelua: 
https://github.com/KohaSuomi/Koha-22x/issues/174#issuecomment-1543664192

**Comment by johannaraisa** [comment]
Lisäsin takaisin napin vihreän värin, yhteisön tapa käsitellä Bootstrapin tyylejä rikkoi tämän.

**Comment by emta001** [comment]
Viety tuotantoon.

**Comment by piiaseme** [comment]
Mozillalla ja Edgellä toimii värimuutos kuten pitää, mutta Chromella ei.

**Comment by johannaraisa** [comment]
Kokeilin omalla Chromella ja se oli vihreä. Chromessa on niin vahvat välimuistitukset, että se varmaan hakee vielä sen vanhan värin välimuistista. Kokeile tyhjentää välimuisti.

**Comment by piiaseme** [comment]
Kiitos vinkistä, tuota ei aina muista. Tyhjennys auttoi.

Tämä siis valmis. Suljen tiketin :)
