### ISSUE TITLE
Tätin tietuesiirtäjä: Tietueille tulee virheviesti: Unprocessable Entity Error in record

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/koha-plugin-broadcast-biblios#10]
Tätin tietuesiirtäjässä tulee joillekin tietueille error-viestiä 

esim.
TäTi ID: 2477873
Unprocessable Entity Error in record. Error while serializing record. Record is invalid: instance.fields[19] is not any of [subschema 0],[subschema 1]

TäTi ID: 1996751
Unprocessable Entity Error in record. Error while serializing  record. Record is invalid: instance.fields[26] is not any of [subschema  0],[subschema 1]

![kuva](https://github.com/user-attachments/assets/de746519-0637-47c8-a3f8-5823cd81f941)

**Comment by johannaraisa** [comment]
> Tätin tietuesiirtäjässä tulee joillekin tietueille error-viestiä
> 
> esim. TäTi ID: 2477873 Unprocessable Entity Error in record. Error while serializing record. Record is invalid: instance.fields[19] is not any of [subschema 0],[subschema 1]

Tässä on ylimääräinen rivivaihto 520$a-kentässä, ennen tätä lausetta, "This is a stark warning against a dystopian...". Kaikki teksti pitäisi ollaa vaan putkeen, Melinda ei muuten tykkää.

**Comment by johannaraisa** [comment]
> Tätin tietuesiirtäjässä tulee joillekin tietueille error-viestiä
> 
> TäTi ID: 1996751 Unprocessable Entity Error in record. Error while serializing record. Record is invalid: instance.fields[26] is not any of [subschema 0],[subschema 1]

Tässäkin on ylimääräinen rivivaihto 540$u-kentän lopussa.

**Comment by johannaraisa** [comment]
Pitää kokeilla rakentaa tohon sellainen, että se karsii nuo ylimääräiset rivivaihdot. Tosin se varmaan pitäisi tehdä jo tuossa Kohaan tallennuksessa, en tiedä miten formaatti tähän suhtautuu, luulisi ettei ole sallittuja jos Melinda estää tuon.

**Comment by AnneliO** [comment]
Auttaisko, jos laittaisi Tätissä päälle järjestelmäasetuksen StripWhitespaceChars?

Strip/Don't strip leading and trailing whitespace characters (including spaces, tabs, line breaks and carriage returns) and inner newlines from data fields when cataloguing bibliographic and authority records. The leader and control fields will not be affected.

**Comment by AnneliO** [comment]
(Itse asiassa kuvittelin sen olevan siellä päällä, mutta näköjään ei ole :D)

**Comment by johannaraisa** [comment]
Joo, jos tuollainen sieltä löytyy niin ihmeessä päälle. :+1:

**Comment by AnneliO** [comment]
Sepä on nyt päällä. Seuraillaan varmaan tilannetta hetki?

**Comment by johannaraisa** [comment]
Joo, tehdään niin.

**Comment by AnneliO** [comment]
Nuo ongelmalliset tietueet voisi nyt varmaan tallentaa uudelleen Tätissä ja yrittää sitten uudelleen vientiä.

**Comment by piiaseme** [comment]
Kuvailija OUTIssa raportoi, että kokeili viemistä Melindaan, mutta sai saman virheilmoituksen. Kun hän poisti ongelmallisen rivinvaihdon osakentästä 540u, niin sitten vienti onnistui.

**Comment by AnneliO** [comment]
Eikö rivinvaihto poistunut automaattisesti tallennettaessa nyt kun asetus on päällä?

**Comment by piiaseme** [comment]
Hän ei tallentanut tietuetta uudelleen ennen TäTiin siirtämisyritystä, hän tallensi vasta korjauksen jälkeen.

**Comment by AnneliO** [comment]
Onko tämä vielä ongelmana vai voisiko tiketin sulkea?

**Comment by piiaseme** [comment]
Suljen tiketin. Avataan uudellen, jos sama ongelma tulee vastaan.
