### ISSUE TITLE
Täti-tietueen asettelu näytölle

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/koha-plugin-broadcast-biblios#2]
Kun ikkunassa näkyy ainoastaan TäTi-tietue, niin koko tietue asettuu näytölle vähän hassusti kun esim. indikaattorit jakautuvat kahdelle riville:

![Indikaattorit kahdella rivillä](https://github.com/KohaSuomi/KohaSuomiServices/assets/98805552/f5c7619b-73ef-47b8-b63c-bd8e6d71fb3c)

Silloin, kun näytöllä on kaksi tietuetta vierekkäin, niin se näyttää ne oikein:

![Indikaattorit yhdellä rivillä](https://github.com/KohaSuomi/KohaSuomiServices/assets/98805552/7b5cbe62-29b2-4309-b1f1-37e6bfd01b8f)

Voiko tuolle kahdelle riville -asettelulle tehdä mitään?

**Comment by johannaraisa** [comment]
Lisäsin korjauksen mikä kasvattaa leveyttä, kun näytöllä on yksi tietue. Laitetaan seuraavaan päivitykseen.

**Comment by johannaraisa** [comment]
Tämä tiketti varmaan kuuluisin broadcast-plugille, sillä siellä tuo asettelu tehdään.

**Comment by johannaraisa** [comment]
Voiko tämän jo sulkea?

**Comment by piiaseme** [comment]
Kyllä voi, suljen tiketin.
