### ISSUE TITLE
Paikalliskantaan tullut poiminnassa osakohteet tuplana/triplana

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/koha-plugin-broadcast-biblios#7]
### Mikä vikana?

Kuvailija raportoi osakohdeongelmasta paikalliskantaan tietueita z-haulla poimittaessa. Tapauksissa käyttäjä on ensin poiminut tietueen Melindasta TäTiin ja vienyt takaisin Melindaan. Paikalliskannassa ei ole ollut tietuetta valmiina, joten tämän jälkeen paikalliskantaan on Z-haulla poimittu tietue TäTistä. Osakohteet ovat poiminnassa tulleet tietueelle kuitenkin jostain syystä tuplana tai triplana. 

Tapauksia on ollut useampi, tämän viimeisimmän tapauksen kohdalla osakohteet tulivat paikalliskantaan triplana:

- Tietue [Vaskissa](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4375101) ja tietue [TäTissä](https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2457080)
(Ylimääräiset osakohteet on Vaskista jo poistettu)

**Comment by johannaraisa** [comment]
Tässä on käynyt niin, että Vaskissa ja Tätissä on tietue päivittynyt samoihin aikoihin ja siksi on päässyt livahtamaan jonoon. Tämä on ollut tiedossa ja laitan korjauksen seuraavaan päivitykseen.

**Comment by ajrajala** [comment]
Kuvailijoille on ilmoitettu korjauksesta ja pyydetty ilmoittamaan mikäli sama ongelma toistuisi vielä uudelleen. Suljen tiketin tällä erää.

**Comment by ajrajala** [comment]
Nyt oli tullut vastaan triplana valuneet osakohteet, kyseessä emotietue [4382436](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4382436). Valutus on tapahtunut 01.08.2024 10:50 ja osakohteet tosiaan tulleet triplana.

**Comment by annavii** [comment]
Vielä toinen esimerkki. Tässä osakohteet ovat valuneet tuplana. Emotietue 4349151 - valutus tapahtunut 1.8.2024 9:20:04 lähtien.

**Comment by johannaraisa** [comment]
Löysin virheellisen kohdan osakohteiden käsittelyssä, laitan korjauksen seuraavaan päivitykseen.

**Comment by MikkoLiimatainen** [comment]
Tänään raportoitu kahdesta tapauksesta, joissa on osakohteet valuneet tuplana tai osittain tuplana.

Tietueessa [4375831](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4375831) osakohteet ovat osittain tuplana ja tietuesiirtäjässä näkyy ensin osittainen tuonti 9 osakohdetta klo 13:20:05 ja viisi minuuttia myöhemmin erikseen tuotuna kaikki 12 osakohdetta. En meinannut ensin edes huomata tuota myöhempää tuontia, kun se ei löytynyt samalla tietuenumerohaulla kuin tuo aikaisempi.

Tietueessa [4373165](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4373165) osakohteet ovat täysin tuplana ja tietuesiirtäjässä näkyy kaksi onnistunutta tuontia samalla kellonajalla 11:25:14.

**Comment by johannaraisa** [comment]
> Tänään raportoitu kahdesta tapauksesta, joissa on osakohteet valuneet tuplana tai osittain tuplana.
> 
> Tietueessa [4375831](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4375831) osakohteet ovat osittain tuplana ja tietuesiirtäjässä näkyy ensin osittainen tuonti 9 osakohdetta klo 13:20:05 ja viisi minuuttia myöhemmin erikseen tuotuna kaikki 12 osakohdetta. En meinannut ensin edes huomata tuota myöhempää tuontia, kun se ei löytynyt samalla tietuenumerohaulla kuin tuo aikaisempi.
> 
> Tietueessa [4373165](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4373165) osakohteet ovat täysin tuplana ja tietuesiirtäjässä näkyy kaksi onnistunutta tuontia samalla kellonajalla 11:25:14.

Tekeekö teillä kuvailijat yhtä aikaa muokkauksia paikalliskannassa ja Tätissä? Katselin, että kummassakin on muokkauksia tehty samaan aikaan Vaskissa ja Tätissä. Tämä [4373165](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4373165) oli tallennettu 11:19 kummassakin ympäristössä. Silloin ne kyllä siirtyy samaan aikaan jonoon odottamaan. Tuota on käytännössä mahdotonta estää, koska siellä jonossa ei ole mitään mihin verrata. Siirto pyritään estämään, jos jonossa on odottamassa tai käsittelyssä jo sama tietue. Voisikohan ohjeistaa, että tekee tarvittavat muokkaukset ensin Tätissä ja odottaa sen siirtymistä paikalliskantaan?

**Comment by annavii** [comment]
Musiikin kuvailijamme sanoo välillä korjaavansa Vaskin tietueen koodia merkkipaikassa 000/17. Ennakkotietueissamme on välillä tuossa väärä koodi joka estää tietojen valumisen Tätistä meille. Hän lupasi jatkossa korjata koodin paikalliskantaan ennen kuin aloittaa tietueen käsittelyn Tätissä. 

Mitään muita muutoksia paikalliskannan tietueessa ei tässä vaiheessa tehdä. Aktivointiarvoa joudutaan välillä säätämään tietuesiirtäjän puolella, mutta se tuskin vaikuttaa asiaan.

Muutetaan siis toimintatapaa ja katsotaan auttaako se.

**Comment by sksandel** [comment]
Olisin sulkenut tiketin, mutta jostain syystä ei onnistu (You do not have permissions to close this issue).

**Comment by johannaraisa** [comment]
> Olisin sulkenut tiketin, mutta jostain syystä ei onnistu (You do not have permissions to close this issue).

Okei, suljen tämän.
